version: "3.0"
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  echo:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    env_file:
    - ".env"